repos:
# general house-keeping tasks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: pretty-format-json
        args: ['--autofix']
# formatting tasks
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.1
    hooks:
    -   id: clang-format
